### ISSUE TITLE
Faulty installation with conda

### ISSUE THREAD

**Issue by mimischi** [bio-phys/MDBenchmark#138]
Trying to install `mdbenchmark` with `conda` fails on our MPCDF clusters. Installing it locally works, as well as installing it with `pip` inside a conda environment (on any cluster) that was set up with `conda`, e.g., `conda create -n benchmark python=3`.

Looks like it has to do with whether there is any display attached to the machine or not. AND it's related to `conda`.

Any thoughts @kain88-de?

```bash
$ mdbenchmark
Traceback (most recent call last):
  File "/u/mimischi/.conda/testdb/bin/mdbenchmark", line 7, in <module>
    from mdbenchmark.cli import cli
  File "/u/mimischi/.conda/testdb/lib/python3.6/site-packages/mdbenchmark/__init__.py", line 20, in <module>
    from . import analyze, generate, plot, submit
  File "/u/mimischi/.conda/testdb/lib/python3.6/site-packages/mdbenchmark/analyze.py", line 23, in <module>
    import matplotlib.pyplot as plt
  File "/u/mimischi/.conda/testdb/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/u/mimischi/.conda/testdb/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/u/mimischi/.conda/testdb/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import (
  File "/u/mimischi/.conda/testdb/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 19, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/u/mimischi/.conda/testdb/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/u/mimischi/.conda/testdb/lib/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 54, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/u/mimischi/.conda/testdb/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 158, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
```

**Comment by kain88-de** [comment]
looks like we can't install matplotlib. Does this happen on phys/bio or also on the newer hydra/draco/cobra?

**Comment by kain88-de** [comment]
My first thought would be that qt was build against a newer clib that what we have available on the cluster. Not much we can do about this besides downgrading matplotlib.

**Comment by kain88-de** [comment]
Or we can set the backend explicitly before we import pylab to avoid it trying to import qt.

**Comment by mimischi** [comment]
Yup, looks like it works on `draco` and `cobra`, but not on our clusters.

**Comment by kain88-de** [comment]
Yeah so a clib issue. You can combat this by only importing matolotlib when
the plotting command is called. This would make matplotlib optional.

**Comment by mimischi** [comment]
Just to clarify, so we're on the same boat:

# Installing via `conda` on our HPC

Installation works and only the third line is a problem.

```bash
conda create -n benchmark python=3.6
conda install -n benchmark mdbenchmark
mdbenchmark
```

# Installing via `pip` on our HPC

Installation works and calling `mdbenchmark` works as expected.

```bash
conda create -n benchmark python=3.6
pip install mdbenchmark
mdbenchmark
```

# Installing via `conda` anywhere else

Installation works and calling `mdbenchmark` works as expected.

```bash
conda create -n benchmark python=3.6
conda install -n benchmark mdbenchmark
mdbenchmark
```

**Comment by kain88-de** [comment]
Yeah I assume the pop calls builds matplotlib and doesn’t use the wheel. If
this is the case the libraries are linked correctly.

**Comment by mimischi** [comment]
After getting the Python 3.7 build to succeed, the issue seems to be fixed.

Installing `mdbenchmark` in a Python >=3.7 environment has fixed the problem: `conda create -n mdb37 python=3 mdbenchmark`
