### ISSUE TITLE
Does not work when installed as documented

### ISSUE THREAD

**Issue by hejung** [bio-phys/MDBenchmark#174]
**Expected behavior**
```bash
mdbenchmark generate -n $NAME --module $MODULE --max-nodes $NNODES
```
should just  work if I follow the installation instructions in a fresh conda environment.

**Actual behavior**
```bash
mdbenchmark generate -n $NAME --module $MODULE --max-nodes $NNODES
```

results in:

```bash
Traceback (most recent call last):
  File "/u/hejung/conda-envs/benchmark/bin/mdbenchmark", line 7, in <module>
    from mdbenchmark.cli import cli
  File "/u/hejung/conda-envs/benchmark/lib/python3.9/site-packages/mdbenchmark/__init__.py", line 21, in <module>
    from mdbenchmark.cli import cli  # noqa: F401
  File "/u/hejung/conda-envs/benchmark/lib/python3.9/site-packages/mdbenchmark/cli/__init__.py", line 20, in <module>
    from mdbenchmark.cli.commands import cli  # noqa: F401
  File "/u/hejung/conda-envs/benchmark/lib/python3.9/site-packages/mdbenchmark/cli/commands.py", line 24, in <module>
    from mdbenchmark.cli.validators import (
  File "/u/hejung/conda-envs/benchmark/lib/python3.9/site-packages/mdbenchmark/cli/validators.py", line 23, in <module>
    from mdbenchmark import console, utils
  File "/u/hejung/conda-envs/benchmark/lib/python3.9/site-packages/mdbenchmark/utils.py", line 25, in <module>
    import datreant as dtr
  File "/u/hejung/conda-envs/benchmark/lib/python3.9/site-packages/datreant/__init__.py", line 16, in <module>
    from .treants import Treant
  File "/u/hejung/conda-envs/benchmark/lib/python3.9/site-packages/datreant/treants.py", line 9, in <module>
    from .collections import Bundle
  File "/u/hejung/conda-envs/benchmark/lib/python3.9/site-packages/datreant/collections.py", line 20, in <module>
    from .metadata import Tags, Categories, AggTags, AggCategories
  File "/u/hejung/conda-envs/benchmark/lib/python3.9/site-packages/datreant/metadata.py", line 13, in <module>
    from .selectionparser import parse_selection
  File "/u/hejung/conda-envs/benchmark/lib/python3.9/site-packages/datreant/selectionparser.py", line 1, in <module>
    from pyparsing import (CaselessLiteral, Word, quotedString,
ImportError: cannot import name 'operatorPrecedence' from 'pyparsing' (/u/hejung/conda-envs/benchmark/lib/python3.9/site-packages/pyparsing/__init__.py)

```

**Your version of MDBenchmark:**
Can not run `mdbenchmark --version` becasue it fails with above error.
Version as reported by conda: mdbenchmark               3.0.1            py39hf3d152e_2    conda-forge

What I did to install:
```bash
 conda create -n benchmark -c conda-forge mdbenchmark
```

EDIT: added details on installation command and command that fails.

**Comment by kain88-de** [comment]
This is related to a bug in datreant: https://github.com/datreant/datreant/issues/179

**Comment by sobuelow** [comment]
The following fixed it for me (using pip in separate mdbenchmark environment):

Make environment:
`conda create -n mdb python=3.7`
then activate it.

Install mdbenchmark with pip
`pip install mdbenchmark`
then downgrade pyparsing and markupsafe:
`pip install pyparsing"<3.0"`
and
`pip install markupsafe==1.1`

**Comment by kain88-de** [comment]
datreant has been updated. This should work again. Maybe the conda package needs to be updated as well.

**Comment by hejung** [comment]
Conda install works for me now.
